# Generated by Django 5.2.6 on 2026-03-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Почта')),
                ('avatar', models.FileField(blank=True, upload_to='avatar', verbose_name='Аватар')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Пароль')),
                ('username', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Имя пользователя')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
